language: php

php:
    - 5.6
#    - 7.0
#    - 7.1
    
sudo: false

before_script:
    - composer install --prefer-dist

script:
    - php PaymentTransactions/charge-credit-card.php
#    - phpunit test-runner.php .
    - cat phplog
